import llvmlite.ir as ir
module = ir.Module(name="struct_transformer_kernel")
bool_ptr = ir.PointerType(ir.IntType(8)) 
double_ptr = ir.PointerType(ir.DoubleType())
func_type = ir.FunctionType(ir.DoubleType(), [ir.IntType(32), bool_ptr, double_ptr])
func = ir.Function(module, func_type, name="vectorized_vip_sum")
block = func.append_basic_block(name="entry")
builder = ir.IRBuilder(block)
size, vip_ptr, val_ptr = func.args
sum_ptr = builder.alloca(ir.DoubleType(), name="total_sum")
builder.store(ir.Constant(ir.DoubleType(), 0.0), sum_ptr)
idx_ptr = builder.alloca(ir.IntType(32), name="loop_idx")
builder.store(ir.Constant(ir.IntType(32), 0), idx_ptr)
loop_cond = builder.append_basic_block(name="loop_cond")
loop_body = builder.append_basic_block(name="loop_body")
loop_end = builder.append_basic_block(name="loop_end")
builder.branch(loop_cond)
builder.position_at_end(loop_cond)
idx_val = builder.load(idx_ptr)
cond = builder.icmp_signed('<', idx_val, size)
builder.cbranch(cond, loop_body, loop_end)
builder.position_at_end(loop_body)
current_vip_ptr = builder.gep(vip_ptr, [idx_val])
is_vip = builder.load(current_vip_ptr)
is_vip_bool = builder.trunc(is_vip, ir.IntType(1))
with builder.if_then(is_vip_bool):
    current_val_ptr = builder.gep(val_ptr, [idx_val])
    val = builder.load(current_val_ptr)
    curr_sum = builder.load(sum_ptr)
    builder.store(builder.fadd(curr_sum, val), sum_ptr)
next_idx = builder.add(idx_val, ir.Constant(ir.IntType(32), 1))
builder.store(next_idx, idx_ptr)
builder.branch(loop_cond)
builder.position_at_end(loop_end)
builder.ret(builder.load(sum_ptr))
print(str(module))
